name: Terraform CI/CD (Dry Run)
 
on:
  push:
    branches: ["*"]   # Run on all branches
  pull_request:       # Also run on PRs
 
permissions:
  id-token: write     # Required for OIDC auth
  contents: read      # Required to checkout the repo
 
jobs:
  terraform-dry-run:
    runs-on: ubuntu-latest
 
    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4
 
      # 2️⃣ Configure AWS credentials using OIDC
      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::288761763515:role/CS1-MA-NCA-Anouar
          aws-region: eu-central-1
 
      # 3️⃣ Test AWS authentication
      - name: Test AWS auth
        run: aws sts get-caller-identity
 
      # 4️⃣ Setup Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.2  # 👈 zet hier jouw versie, consistent met lokaal
 
      # 5️⃣ Terraform Init
      - name: Terraform Init
        run: terraform init
 
      # 6️⃣ Terraform Validate (optioneel, maar handig!)
      - name: Terraform Validate
        run: terraform validate
 
      # 7️⃣ Terraform Plan (Dry Run)
      - name: Terraform Plan (Dry Run)
        run: terraform plan -no-color
