name: Terraform CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}  # 👈 gebruikt de secret voor RDS password

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout de repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::288761763515:role/CS1-MA-NCA-Anouar
          aws-region: eu-central-1

      # 3️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7  # Pas aan naar jouw lokale versie

      # 4️⃣ Terraform Init + upgrade providers
      - name: Terraform Init
        run: terraform init -upgrade

      # 5️⃣ Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 6️⃣ Terraform Format Check (optioneel)
      - name: Terraform Format Check
        run: terraform fmt -check

      # 7️⃣ Terraform Plan
      - name: Terraform Plan
        run: terraform plan -no-color

      # 8️⃣ Terraform Apply (non-interactief)
      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
