name: Terraform CI/CD

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}  # gebruik je secret

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout de repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure AWS credentials via OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::288761763515:role/CS1-MA-NCA-Anouar
          aws-region: eu-central-1

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      # Terraform Init (remote backend)
      - name: Terraform Init
        run: terraform init -input=false

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # Terraform Format Check (optioneel)
      - name: Terraform Format Check
        run: terraform fmt -check

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan -no-color -input=false

      # Terraform Apply (alleen op main branch)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -no-color -input=false
